# Generated by Django 5.2.11 on 2026-02-10 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("encrypted_data", models.TextField()),
                ("category", models.CharField(blank=True, default="", max_length=100)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("is_favorite", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_accessed", models.DateTimeField(blank=True, null=True)),
                ("username_hint", models.CharField(blank=True, max_length=255)),
                ("url_hint", models.CharField(blank=True, max_length=255)),
                ("has_notes", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "password_entries",
                "ordering": ["-is_favorite", "title"],
            },
        ),
        migrations.CreateModel(
            name="PasswordShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "share_type",
                    models.CharField(
                        choices=[
                            ("view", "View Only"),
                            ("edit", "Can Edit"),
                            ("admin", "Admin"),
                        ],
                        default="view",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="passwords.passwordentry",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "password_shares",
            },
        ),
        migrations.CreateModel(
            name="SecurityAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("create", "Entry Created"),
                            ("view", "Entry Viewed"),
                            ("edit", "Entry Edited"),
                            ("delete", "Entry Deleted"),
                            ("share", "Entry Shared"),
                            ("export", "Data Exported"),
                            ("import", "Data Imported"),
                            ("login", "User Login"),
                            ("security_change", "Security Settings Changed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="passwords.passwordentry",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "security_audits",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PasswordCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("color", models.CharField(default="#007bff", max_length=7)),
                ("icon", models.CharField(default="folder", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "password_categories",
                "ordering": ["name"],
                "unique_together": {("user", "name")},
            },
        ),
        migrations.AddIndex(
            model_name="passwordentry",
            index=models.Index(
                fields=["user", "title"], name="password_en_user_id_5eb80d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passwordentry",
            index=models.Index(
                fields=["user", "category"], name="password_en_user_id_563203_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passwordentry",
            index=models.Index(
                fields=["user", "is_favorite"], name="password_en_user_id_98fdca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passwordentry",
            index=models.Index(
                fields=["user", "created_at"], name="password_en_user_id_06770f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passwordentry",
            index=models.Index(fields=["tags"], name="password_en_tags_9d7644_idx"),
        ),
        migrations.AddIndex(
            model_name="passwordshare",
            index=models.Index(
                fields=["shared_with", "is_active"],
                name="password_sh_shared__4db408_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="passwordshare",
            index=models.Index(
                fields=["shared_by", "created_at"],
                name="password_sh_shared__840a37_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="passwordshare",
            unique_together={("entry", "shared_with")},
        ),
        migrations.AddIndex(
            model_name="securityaudit",
            index=models.Index(
                fields=["user", "timestamp"], name="security_au_user_id_6287fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityaudit",
            index=models.Index(
                fields=["event_type"], name="security_au_event_t_62a643_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityaudit",
            index=models.Index(
                fields=["timestamp"], name="security_au_timesta_13da05_idx"
            ),
        ),
    ]
