# Generated by Django 5.2.11 on 2026-02-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passwords", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="passwordentry",
            name="custom_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="passwordentry",
            name="source",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="passwordentry",
            name="source_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
